{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "mongodb.fullname" .) .Values.serviceAccount.name }}
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
secrets:
  - name: "{{ template "mongodb.fullname" . }}"
{{- end }}
